# Generated by Django 5.1 on 2024-09-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.IntegerField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=20)),
                ('salary', models.IntegerField(max_length=10)),
                ('userid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('mobile_no', models.IntegerField()),
                ('mail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('stid', models.IntegerField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=20)),
                ('salary', models.IntegerField(max_length=10)),
                ('userid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('mobile_no', models.IntegerField()),
                ('mail', models.CharField(max_length=20)),
            ],
        ),
    ]
