# Generated by Django 5.1 on 2024-09-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alogin', '0003_alter_admin_mobile_no_alter_student_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
    ]
