# Generated by Django 5.1 on 2024-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alogin', '0005_alter_admin_salary_alter_teacher_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
