# Generated by Django 5.1 on 2024-10-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alogin', '0007_subject_attendance_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='faculty',
            new_name='teacher',
        ),
    ]
